# Inspired by:
# - https://gitlab.com/gitlab-org/gitlab-ci-yml/blob/master/Maven.gitlab-ci.yml
#
# Reference:
# - https://docs.gitlab.com/ce/ci/yaml/README.html


image: openjdk:8-jdk

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "-s .gitlab/settings.xml --global-toolchains=.gitlab/toolchains.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_CLI_OPTS_COVERAGE: "-s .gitlab/settings.xml --global-toolchains=.gitlab/toolchains.xml"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
  paths:
    - .m2/repository

stages:
  - verify
  - packaging

# Verify merge requests
tests:
  stage: verify
  script:
    - ./mvnw clean install -Prelease $MAVEN_CLI_OPTS
  only:
    - branches
  except:
    - master
    - develop
    - feature/invoiceborg-master
    - feature/invoiceborg-develop


#pages:
#  stage: packaging
#  script:
#  - ./mvnw $MAVEN_CLI_OPTS_COVERAGE install -DskipTests -DskipITs
#  - ./mvnw $MAVEN_CLI_OPTS_COVERAGE verify site -Pcoverage -DskipITs
#  - ls -Rlr ./target/pit-reports/
#  - ls -Rlr ./target/site/
#  - ./mvnw $MAVEN_CLI_OPTS_COVERAGE site:stage -Pcoverage -DskipITs
#  - ls -Rlr ./target/staging/
#  - mv ./target/staging/ public
#  artifacts:
#    paths:
#    - public
#  only:
#    - develop

eigor-artifacts-snapshot:
  stage: packaging
  script: ./mvnw $MAVEN_CLI_OPTS deploy -Prelease
  only:
    - tags
    - develop
    - feature/invoiceborg-develop


eigor-artifacts-release:
  stage: packaging
  script: ./mvnw $MAVEN_CLI_OPTS deploy -Preleasexslt
  only:
    - master
    - feature/invoiceborg-master
